/// Flutter icons QuantityIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  QuantityIcon
///      fonts:
///       - asset: fonts/QuantityIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class QuantityIcon {
  QuantityIcon._();

  static const _kFontFam = 'QuantityIcon';
  static const String? _kFontPkg = null;

  static const IconData quantity =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
